### ISSUE TITLE
parse_eggNOG.py  error?

### ISSUE THREAD

**Issue by zifeng8824** [Hua-CM/HuaSmallTools#2]
你好，我在使用您提供的脚本对EggNOG注释的结果进行GO和KEGG提取使出现了错误：命令行是：
python parse_eggNOG.py -i ../query_seqs.fa.emapper.annotations -g go.tb -O ath,osa -o result 
出现了以下的报错：
Traceback (most recent call last):
  File "parse_eggNOG.py", line 133, in <module>
    main(args.input_file, args.output_directory, args.go_file, args.org_list.split(","))
  File "parse_eggNOG.py", line 114, in main
    file4KO = parse_KO(file4parse, org_list)[["gene", "KO", "pathway", "description"]]
  File "parse_eggNOG.py", line 81, in parse_KO
    KO2map, KEGGmap = get_KEGGmap(own_mapdb(org_list))
  File "parse_eggNOG.py", line 35, in own_mapdb
    tmp_df = pd.DataFrame(tmp, columns=["pathway", "description"]).dropna()
  File "/lustre/xzq/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 407, in __init__
    raise TypeError("data argument can't be an iterator")

请问这怎么解决，谢谢！

**Comment by Hua-CM** [comment]
> 
> 
> 你好，我在使用您提供的脚本对EggNOG注释的结果进行GO和KEGG提取使出现了错误：命令行是：
> python parse_eggNOG.py -i ../query_seqs.fa.emapper.annotations -g go.tb -O ath,osa -o result
> 出现了以下的报错：
> Traceback (most recent call last):
> File "parse_eggNOG.py", line 133, in
> main(args.input_file, args.output_directory, args.go_file, args.org_list.split(","))
> File "parse_eggNOG.py", line 114, in main
> file4KO = parse_KO(file4parse, org_list)[["gene", "KO", "pathway", "description"]]
> File "parse_eggNOG.py", line 81, in parse_KO
> KO2map, KEGGmap = get_KEGGmap(own_mapdb(org_list))
> File "parse_eggNOG.py", line 35, in own_mapdb
> tmp_df = pd.DataFrame(tmp, columns=["pathway", "description"]).dropna()
> File "/lustre/xzq/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 407, in **init**
> raise TypeError("data argument can't be an iterator")
> 
> 请问这怎么解决，谢谢！

你好，感谢提问。这个问题是较低版本的pandas不支持数据来源为迭代器导致的，我已经更新了脚本，应该可以用了。

**Comment by zifeng8824** [comment]
> 
> 
> > 你好，我在使用您提供的脚本对EggNOG注释的结果进行GO和KEGG提取使出现了错误：命令行是：
> > python parse_eggNOG.py -i ../query_seqs.fa.emapper.annotations -g go.tb -O ath,osa -o result
> > 出现了以下的报错：
> > Traceback (most recent call last):
> > File "parse_eggNOG.py", line 133, in
> > main(args.input_file, args.output_directory, args.go_file, args.org_list.split(","))
> > File "parse_eggNOG.py", line 114, in main
> > file4KO = parse_KO(file4parse, org_list)[["gene", "KO", "pathway", "description"]]
> > File "parse_eggNOG.py", line 81, in parse_KO
> > KO2map, KEGGmap = get_KEGGmap(own_mapdb(org_list))
> > File "parse_eggNOG.py", line 35, in own_mapdb
> > tmp_df = pd.DataFrame(tmp, columns=["pathway", "description"]).dropna()
> > File "/lustre/xzq/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 407, in **init**
> > raise TypeError("data argument can't be an iterator")
> > 请问这怎么解决，谢谢！
> 
> 你好，感谢提问。这个问题是较低版本的pandas不支持数据来源为迭代器导致的，我已经更新了脚本，应该可以用了。

你好，我重新使用了你更新的脚本后，还是出现了一样的问题：
[xzs@fat01 go]$ python parse_eggNOG1.py -i ../query_seqs.fa.emapper.annotations -g go.tb -O ath,osa -o result
Traceback (most recent call last):
  File "parse_eggNOG1.py", line 133, in <module>
    main(args.input_file, args.output_directory, args.go_file, args.org_list.split(","))
  File "parse_eggNOG1.py", line 114, in main
    file4KO = parse_KO(file4parse, org_list)[["gene", "KO", "pathway", "description"]]
  File "parse_eggNOG1.py", line 81, in parse_KO
    KO2map, KEGGmap = get_KEGGmap(own_mapdb(org_list))
  File "parse_eggNOG1.py", line 52, in get_KEGGmap
    KEGGmap_df = pd.DataFrame(KEGGmap, columns=["pathway", "description"]).dropna()
  File "/lustre/xzs/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 407, in __init__
    raise TypeError("data argument can't be an iterator")
TypeError: data argument can't be an iterator
能否将你尝试这个脚本的 eggNOG注释的文件发我一下，我再试试呢？ 有没有可能我的注释结果格式有问题？谢谢！
祝好！

**Comment by Hua-CM** [comment]
> 
> 
> > > 你好，我在使用您提供的脚本对EggNOG注释的结果进行GO和KEGG提取使出现了错误：命令行是：
> > > python parse_eggNOG.py -i ../query_seqs.fa.emapper.annotations -g go.tb -O ath,osa -o result
> > > 出现了以下的报错：
> > > Traceback (most recent call last):
> > > File "parse_eggNOG.py", line 133, in
> > > main(args.input_file, args.output_directory, args.go_file, args.org_list.split(","))
> > > File "parse_eggNOG.py", line 114, in main
> > > file4KO = parse_KO(file4parse, org_list)[["gene", "KO", "pathway", "description"]]
> > > File "parse_eggNOG.py", line 81, in parse_KO
> > > KO2map, KEGGmap = get_KEGGmap(own_mapdb(org_list))
> > > File "parse_eggNOG.py", line 35, in own_mapdb
> > > tmp_df = pd.DataFrame(tmp, columns=["pathway", "description"]).dropna()
> > > File "/lustre/xzq/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 407, in **init**
> > > raise TypeError("data argument can't be an iterator")
> > > 请问这怎么解决，谢谢！
> > 
> > 
> > 你好，感谢提问。这个问题是较低版本的pandas不支持数据来源为迭代器导致的，我已经更新了脚本，应该可以用了。
> 
> 你好，我重新使用了你更新的脚本后，还是出现了一样的问题：
> [xzs@fat01 go]$ python parse_eggNOG1.py -i ../query_seqs.fa.emapper.annotations -g go.tb -O ath,osa -o result
> Traceback (most recent call last):
> File "parse_eggNOG1.py", line 133, in
> main(args.input_file, args.output_directory, args.go_file, args.org_list.split(","))
> File "parse_eggNOG1.py", line 114, in main
> file4KO = parse_KO(file4parse, org_list)[["gene", "KO", "pathway", "description"]]
> File "parse_eggNOG1.py", line 81, in parse_KO
> KO2map, KEGGmap = get_KEGGmap(own_mapdb(org_list))
> File "parse_eggNOG1.py", line 52, in get_KEGGmap
> KEGGmap_df = pd.DataFrame(KEGGmap, columns=["pathway", "description"]).dropna()
> File "/lustre/xzs/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 407, in **init**
> raise TypeError("data argument can't be an iterator")
> TypeError: data argument can't be an iterator
> 能否将你尝试这个脚本的 eggNOG注释的文件发我一下，我再试试呢？ 有没有可能我的注释结果格式有问题？谢谢！
> 祝好！

你好，不会是注释结果格式问题（只要你从eggNOG下载后没有进行过任何改动）。再次检查了脚本，不是一样的问题，是脚本多个地方我都使用了迭代器做为数据源，之前只检查了报错行，没有检查全部脚本。我再次修改了脚本，应该可以了。同时为了避免更多由于pandas版本特性带来的问题，建议将pandas升级至1.0以上。

**Comment by alexximalayaunlv** [comment]
你好，

十分感谢你在网上分享解析代码！我用服务器跑的eggnog_mapper v2. 然后按照教程进行解析。可是遇到了如下的问题：

Traceback (most recent call last):
  File "parse_eggNOG.py", line 134, in <module>
    main(args.input_file, args.output_directory, args.go_file, args.org_list.split(","))
  File "parse_eggNOG.py", line 117, in main
    file4KO.to_csv(os.path.join(out_dir, "KOannotation.tsv"), sep="\t", index=False)
  File "/home/dengxun/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 1745, in to_csv
    formatter.save()
  File "/home/dengxun/.local/lib/python2.7/site-packages/pandas/io/formats/csvs.py", line 156, in save
    compression=self.compression)
  File "/home/dengxun/.local/lib/python2.7/site-packages/pandas/io/common.py", line 397, in _get_handle
    f = open(path_or_buf, mode)
IOError: [Errno 2] No such file or directory: './test/KOannotation.tsv'

我尝试更新了pandas, 依然出现这样的报错。希望得到你的帮助！谢谢！
