### ISSUE TITLE
parse_eggNOG.py error

### ISSUE THREAD

**Issue by aayoungfish** [Hua-CM/HuaSmallTools#4]
非常不好意思，想请问一下这个问题应该怎么解决。
输入为：python parse_eggNOG.py -i MM.emapper.annotations.tsv -g go.tb -O spar,pti,fcy,tps -o test
报错为：
Traceback (most recent call last):
  File "parse_eggNOG.py", line 154, in <module>
    main(args.input_file, args.output_directory, args.go_file, args.org_list.split(","))
  File "parse_eggNOG.py", line 131, in main
    usecols=check_column(input_file),
  File "parse_eggNOG.py", line 124, in check_column
    return 0, go_idx, kegg_idx
UnboundLocalError: local variable 'go_idx' referenced before assignment

**Comment by Hua-CM** [comment]
> 
> 
> 非常不好意思，想请问一下这个问题应该怎么解决。
> 输入为：python parse_eggNOG.py -i MM.emapper.annotations.tsv -g go.tb -O spar,pti,fcy,tps -o test
> 报错为：
> Traceback (most recent call last):
> File "parse_eggNOG.py", line 154, in
> main(args.input_file, args.output_directory, args.go_file, args.org_list.split(","))
> File "parse_eggNOG.py", line 131, in main
> usecols=check_column(input_file),
> File "parse_eggNOG.py", line 124, in check_column
> return 0, go_idx, kegg_idx
> UnboundLocalError: local variable 'go_idx' referenced before assignment

不介意的话将您的输入文件发我一份

**Comment by aayoungfish** [comment]
非常感谢您的回复，麻烦您了！


发件人: Zhongyi Hua
发送时间: 2021年8月28日 21:00
收件人: Hua-CM/HuaSmallTools
抄送: aayoungfish; Author
主题: Re: [Hua-CM/HuaSmallTools] parse_eggNOG.py error (#4)

非常不好意思，想请问一下这个问题应该怎么解决。
输入为：python parse_eggNOG.py -i MM.emapper.annotations.tsv -g go.tb -O spar,pti,fcy,tps -o test
报错为：
Traceback (most recent call last):
File "parse_eggNOG.py", line 154, in
main(args.input_file, args.output_directory, args.go_file, args.org_list.split(","))
File "parse_eggNOG.py", line 131, in main
usecols=check_column(input_file),
File "parse_eggNOG.py", line 124, in check_column
return 0, go_idx, kegg_idx
UnboundLocalError: local variable 'go_idx' referenced before assignment
不介意的话将您的输入文件发我一份
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hua-CM** [comment]
一直没有收到您的文件，确认一下是问题解决了吗？

**Comment by aayoungfish** [comment]
您好，我有私发邮件给您，附带了文件的。可能出了点问题导致您没有收到，请您再看看这个网址是否可以打开文件。谢谢！

**Comment by Hua-CM** [comment]
重新clone一下，问题已解决
