### ISSUE TITLE
关于 parse_go_obofile.py 脚本作用的问题.

### ISSUE THREAD

**Issue by Jiahe-Sun** [Hua-CM/HuaSmallTools#5]
你好,非常感谢您的开源教程,  我在根据eggnog-mapper在线注释结果进行GO、KEGG分析时, 有一个疑问关于您教程中提到 需要首先需要去GO下载GO的obo文件,并使用go-basic.obo脚本可以对obo文件解析.  我不太清楚为什么不能直接根据eggnog-mapper结果中的注释信息通过enrichr函数绘图, 这里下载GO的obo文件的作用是? 

希望得到您的指导:

<img width="688" alt="image" src="https://github.com/Hua-CM/HuaSmallTools/assets/69581197/72cda421-9296-465b-b9e9-c6ef86e50c67">

**Comment by Hua-CM** [comment]
个人习惯，您有别的方法实现一样可以。

**Comment by Jiahe-Sun** [comment]
好的, 这个是获得背景基因的个数用来计算比率的吗?

**Comment by Hua-CM** [comment]
获取注释信息

**Comment by Jiahe-Sun** [comment]
我使用eggnog-mapper注释的结果文件中也包含注释信息,是否我能理解为我可以使用这个注释信息,而不用重新下载解析GO的obo文件呢?

**Comment by Hua-CM** [comment]
这个问题与本代码无关。
